### ISSUE TITLE
Flatpak it

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/plausible#2]
Since it's largely a web app, I don't think I want to try to get it into AppCenter. So I think Flathub would make the most sense.

**Comment by TheEvilSkeleton** [comment]
Hi @cassidyjames,

I've written a flatpak manifest<sup>[1]</sup>. Unfortunately I do not have an account to test, but the application launches no problem. Uploading it to Flathub will be easy: just fork the manifest I've written, and submit a merge request at upstream once it's ready to go. **If there are any issues, please let me know.**

Related to https://github.com/cassidyjames/plausible/issues/5, we'll have to wait for a name change before uploading it to Flathub (if wanted).

~~I'd like to ask a question about the ID. Can you change the ID from [`com.github.cassidyjames.plausible`](https://github.com/cassidyjames/plausible/search?q=com.github.cassidyjames.plausible) to `com.cassidyjames.Plausible` (or without the capital P)? Since you have a domain, I think it would be better if the ID can be trimmed down; I won't mind changing a bit of the manifest.~~

If you want to run it locally, and assuming you have `flatpak-builder` installed, run the following commands:

```
git clone https://github.com/TheEvilSkeleton/flatpaks/
cd flatpaks
git checkout com.cassidyjames.plausible
flatpak-builder --force-clean --install-deps-from=flathub --install build-dir com.cassidyjames.plausible.yaml
```

---

[1] https://github.com/TheEvilSkeleton/flatpaks/tree/com.cassidyjames.plausible

/cc @metmarkosaric

**Comment by metmarkosaric** [comment]
Just installed this as a Flatpak on my machine and it works great! The icon and everything fits well. Log in fine and view the stats. After closing the app I don't need to log in again next time I open it. Keyboard shortcuts work as on the site. 

Only thing I noticed is that ctrl and +/- for zoom doesn't work so it's stuck at 100% even though I normally run it on 150% on Firefox.

**Comment by cassidyjames** [comment]
@metmarkosaric I can add zoom; I've filed that at #7.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton RDNN ID filed at #8

**Comment by TheEvilSkeleton** [comment]
Changed the RDNN: https://github.com/TheEvilSkeleton/flatpaks/tree/com.cassidyjames.plausible. Now a release should be good enough for the flatpak so it won't pull its sources from the latest commits.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton I've actually included the metainfo and Flatpak manifest in this repo now. It builds and works, though I'm missing the elementary stylesheet which I'll want for my custom styling.

**Comment by TheEvilSkeleton** [comment]
@cassidyjames alright. https://github.com/TheEvilSkeleton/flatpaks/commit/74a2997295b3554f3010c209b8d2e7a4f9e2f1ae

About the manifest, I'll keep it in my repo so you (or someone else) can just easily fork and submit a merge request in https://github.com/flathub/flathub.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton if my build system installs the metainfo to the filesystem, do you still also need to specify that in the manifest?

**Comment by TheEvilSkeleton** [comment]
~~@cassidyjames are you talking about this one from my [flatpaks](https://github.com/TheEvilSkeleton/flatpaks/tree/com.cassidyjames.plausible) repo or from your personal project?~~

I think it should be just fine. I'll check it out and report you in a couple of minutes.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton either, but ultimately what gets submitted to Flathub. I am looking at other apps that are targeting elementary OS and I don't see any manual handling of metainfo there.

**Comment by TheEvilSkeleton** [comment]
@cassidyjames I just tested it, and the metainfo file in your personal repo is in use:

![image](https://user-images.githubusercontent.com/50847364/108449215-19fe6b00-7231-11eb-8b04-c6c95d2f73e2.png)

The version number, developer name (you), and release date are there, as it should. Without the metainfo, it looks like the following:

![image](https://user-images.githubusercontent.com/50847364/108449575-b3c61800-7231-11eb-8d40-b189e0acc8b3.png)

That's only the manifest on your repo. On the flatpaks repo, we need to specify where to put the metainfo file.

---

Fyi, I'm using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal).

**Comment by TheEvilSkeleton** [comment]
@cassidyjames turns out this works: https://github.com/TheEvilSkeleton/flatpaks/commit/9dbf48a37b75cc2d38112e4cb5cd3f935923e7b4. This is by far the smallest Flatpak manifest I've ever seen in my life.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton I'm prepping a 1.0.0 release. Once that's cut, you should be able to point it at the 1.0.0 tag instead of master.

**Comment by cassidyjames** [comment]
I've proposed it to https://github.com/flathub/flathub/pull/2122. Thanks for all your help with this @TheEvilSkeleton!
